---

- name: Installing package
  apt: name=fail2ban update_cache=yes

- name: Configuring local jail
  template: >
    src={{ fail2ban_jail_template if fail2ban_jail_template else 'jail.local.j2' }}
    dest=/etc/fail2ban/jail.local
    owner=root
    group=root
    mode=0640
  notify: restart fail2ban

- name: Configuring service
  service: >
    name=fail2ban
    state={{ fail2ban_service_state }}
    enabled={{ fail2ban_service_enabled }}